#input_path: 'hdfs://172.20.64.51:8020/user/mart_cis/spa1/'
input_path: 'hive'

# date window for updating result data
update_start: '2015-10-01'
update_end: '2015-12-31'

# the earliest date
update_origin: '2016-01-01'

# mode for writing table
write_mode: 'insert'

# 1: overwrite any existing data in a table; 0: throw an exception if data already exists.
overwrite: 0

# fill: fill historical data; None: fill the latest data
historical_data: 'None'

# default author
author: 'lishikun4'

# the earliest avaiable partition for tables with incomplete history in rmb cluster
earliest_dt_gdm_m07_cps_batch_da: '2016-05-04'
earliest_dt_pf_promotion_coverage_all_new: '2017-12-24'
earliest_dt_pf_promotion_record_all_new: '2017-10-01'
earliest_dt_pf_promotion_rule_all_new_info: '2017-04-04'

# raw input querys
querys:
    self_sku_order_det:
        "
        SELECT
            a.sale_ord_tm,
            a.user_log_acct,
            a.parent_sale_ord_id,
            a.item_sku_id,
            a.sale_ord_dt,
            a.sale_qtty,
            a.after_prefr_amount,
            a.before_prefr_amount,
            a.total_offer_amount,
            a.sku_offer_amount,
            a.suit_offer_amount,
            a.full_minus_offer_amount,
            a.dq_and_jq_pay_amount,
            a.jq_pay_amount,
            a.dq_pay_amount,
            a.lim_cate_jq_pay_amount,
            a.lim_cate_dq_pay_amount,
            a.user_actual_pay_amount,
            a.free_goods_flag,
            a.sku_jd_prc,
            a.dt
        FROM
            dev.all_sku_order_det a
        INNER JOIN
            gdm.gdm_m03_self_item_sku_da b
        ON
            a.item_sku_id = b.item_sku_id
        WHERE
            a.dt >= '{start}'
        AND
            a.dt <= '{end}'
        AND
            b.dt = '{tail}'
        AND
            a.sale_ord_type_cd NOT IN (
                2, 4, 7, 11, 13, 15, 16, 19, 28, 29, 30, 33, 34, 35, 36, 37, 38,
                39, 43, 44, 45, 46, 47, 48, 49, 51, 53, 55, 58, 61, 62, 63, 65,
                66, 67, 68, 69, 70, 71, 72, 73, 201)
        AND
            a.sale_ord_valid_flag = 1
        "

    fdm_pricemanage_promotionlargess_chain:
        "
        SELECT
            *
        FROM
            fdm.fdm_pricemanage_promotionlargess_chain
        "

    app_cmo_ol_client_sku_3_to_bjmart_di:
        "
        SELECT
            a.*
        FROM
            app.app_cmo_ol_client_sku_3_to_bjmart_di a
        INNER JOIN
            gdm.gdm_m03_self_item_sku_da b
        ON
            a.item_sku_id = b.item_sku_id
        WHERE
            a.dt >= '{start}'
        AND
            a.dt <= '{end}'
        AND
            b.dt = '{tail}'
        "

    app_sfs_vendibility2:
        "
        SELECT
            a.*
        FROM
            app.app_sfs_vendibility2 a
        INNER JOIN
            gdm.gdm_m03_self_item_sku_da b
        ON
            a.sku_id = b.item_sku_id
        WHERE
            a.dt >= '{start}'
        AND
            a.dt <= '{end}'
        AND
            b.dt = '{tail}'
        "

    gdm_m03_item_sku_price_change_log:
        "
        SELECT
            a.sku_id,
            a.create_tm,
            a.old_prc,
            a.new_prc
        FROM
            gdm.gdm_m03_item_sku_price_change_log a
        INNER JOIN
            gdm.gdm_m03_self_item_sku_da b
        ON
            a.sku_id = b.item_sku_id
        WHERE
            a.dt >= '{start}'
        AND
            a.dt <= '{end}'
        AND
            a.prc_type = 'salePrice'
        AND
            b.dt = '{tail}'
        "

    gdm_m04_ord_promotion_sum:
        "
        SELECT
            a.*
        FROM
            gdm.gdm_m04_ord_promotion_sum a
        INNER JOIN
            gdm.gdm_m03_self_item_sku_da b
        ON
            a.item_sku_id = b.item_sku_id
        WHERE
            a.dt >= '{start}'
        AND
            a.dt <= '{end}'
        AND
            b.dt = '{tail}'
        "

    gdm_m07_cps_sku_info:
        "
        SELECT
            a.parent_sale_ord_id,
            a.item_sku_id,
            a.batch_id,
            a.pay_amount,
            a.jq_pay_amount,
            a.dq_pay_amount,
            a.dt
        FROM
            gdm.gdm_m07_cps_sku_info a
        INNER JOIN
            gdm.gdm_m03_self_item_sku_da b
        ON
            a.item_sku_id = b.item_sku_id
        WHERE
            a.dt >= '{start}'
        AND
            b.dt = '{tail}'
        "

    gdm_m07_cps_basic_info:
        "
        SELECT
            *
        FROM
            gdm.gdm_m07_cps_basic_info
        WHERE
            dt >= '{start}'
        AND
            dt <= '{end}'
        "

    pf_promotion_coverage_all_new:
        "
        SELECT * FROM app.pf_promotion_coverage_all_new WHERE dt = '{start}'
        "

    pf_promotion_record_all_new:
        "
        SELECT * FROM app.pf_promotion_record_all_new WHERE dt = '{start}'
        "

    pf_promotion_rule_all_new_info:
        "
        SELECT * FROM app.pf_promotion_rule_all_new_info WHERE dt = '{start}'
        "

    gdm_m07_cps_batch_da:
        "
        SELECT * FROM gdm.gdm_m07_cps_batch_da WHERE dt = '{end}'
        "

    fdm_coupon_coupon_chain:
        "
        SELECT * FROM fdm.fdm_coupon_coupon_chain WHERE dp='ACTIVE'
        "

    app_jd_price_history_all_da:
        "
        SELECT
            a.*
        FROM
            app.app_jd_price_history_all_da a
        INNER JOIN
            gdm.gdm_m03_self_item_sku_da b
        ON
            a.sku = b.item_sku_id
        WHERE
            b.dt = '{tail}'
        "

    gdm_m03_self_item_sku_da:
        "
        SELECT
            *
        FROM
            gdm.gdm_m03_self_item_sku_da
        WHERE
            dt >= '{start}'
        AND
            dt <= '{end}'
        "

    jd_price:
        "SELECT * FROM app.app_pa_transactions_B1 WHERE dt>='{start}' AND dt<='{end}'"
